### Site Settings ###
title               : Jeremy Hong
profile         : >-
                      "Hello World!"
baseurl             : ""               # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : jeremyhong0/jeremyhong0.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Jeremy Hong
  image             : "/assets/image/profile.jpg"
# behance           : your_username
# dribbble          : your_username
  email             : jeremyhong.digipen@gmail.com
# facebook          : your_username
  github            : JeremyHong0
# gitlab            : your_username
# instagram         : s__hongg
# kaggle            : your_username
  linkedin          : jeremy-hong-
#  medium           : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
#permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
